suppressMessages(library(data.table))
d <- fread("shiny_app/data.csv"); t <- fread("out_20260917_fix/gene_tier_assignment.csv")
b <- function(v) is.na(v) | v==""
message("== blank gene symbol ==")
nb <- d[b(gene)]
message("rows: ", nrow(nb))
message("  with gene_id: ", nb[!b(c_gene_id), .N])
message("  with variant_ID: ", nb[!b(variant_ID), .N])
message("  distinct loci: ", uniqueN(nb$ADlocus))
message("== gene but no top_confidence ==")
nt <- d[!b(gene) & b(top_confidence)]
g <- unique(nt$gene)
message("rows: ", nrow(nt), "  genes: ", length(g))
message("  of these genes present in tier file: ", length(intersect(g, t$gene_name)))
message("  absent from tier file: ", length(setdiff(g, t$gene_name)))
message("== evidence_tier cross-check ==")
message("rows blank top_confidence but NON-blank evidence_tier: ", d[b(top_confidence) & !b(evidence_tier), .N])
print(table(top=ifelse(b(d$top_confidence),"blank","set"), ev=ifelse(b(d$evidence_tier),"blank","set")))
message("== sample untiered genes ==")
print(head(sort(g), 20))
